version: '3'

services:

#  ghcr.io/jibbberjabber/folllowing-api:master

  follow-api:
    container_name: "follow-api"
    image: ghcr.io/jibbberjabber/folllowing-api:master
    ports:
      - 8080:8080
    environment:
      DB_USER: postgres
      DB_PASSWORD: admin
      DB_NAME: followers-db
      DB_HOST: db
      DB_PORT: 5433

  follow_db:
    container_name: follow_db
    image: postgres:12
    ports:
      - 5434:5433
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: followers-db
    volumes:
      - followdata:/var/lib/postgresql/data


  posts-api:
    container_name: "posts-api"
    image: ghcr.io/jibbberjabber/posts-api:master
    ports:
      - 8081:8080
    environment:
      DB_USER: postgres
      DB_PASSWORD: admin
      DB_NAME: posts-db
      DB_HOST: db
      DB_PORT: 5433

  posts-db:
    container_name: posts-db
    image: postgres:12
    ports:
      - 5433:5433
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: posts-db
    volumes:
      - postdata:/var/lib/postgresql/data2


#  keycloak_db:
#    image: postgres
#    volumes:
#      - keycloakdata:/var/lib/postgresql/data
#    environment:
#      POSTGRES_DB: keycloak
#      POSTGRES_USER: keycloak
#      POSTGRES_PASSWORD: password
#
#  keycloak:
#    image: quay.io/keycloak/keycloak
#    container_name: keycloak
#    environment:
#      KEYCLOAK_USER: admin
#      KEYCLOAK_PASSWORD: admin
#    ports:
#      - 8080:8080
#    depends_on:
#      - keycloak_db


volumes:
  postdata:
    external: false
  followdata:
    external: false
#  keycloakdata:
#    external: true