version: '3'

services:

  #  ghcr.io/jibbberjabber/folllowing-api:master

  follow-api:
    container_name: "follow-api"
    image: ghcr.io/jibbberjabber/folllowing-api:master

    ports:
      - 8080:8080
    environment:
      DB_USER: postgres
      DB_PASSWORD: admin
      DB_NAME: followers-db
      DB_HOST: follow_db
      DB_PORT: 5432

  follow_db:
    container_name: follow_db
    image: postgres:12
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: followers-db
    volumes:
      - followdata:/var/lib/postgresql/data


  posts-api:
    container_name: "posts-api"
    image: ghcr.io/jibbberjabber/posts-api:master
    ports:
      - 8083:8080
    environment:
      DB_USER: postgres
      DB_PASSWORD: admin
      DB_NAME: posts-db
      DB_HOST: posts-db
      DB_PORT: 5432

  posts-db:
    container_name: posts-db
    image: postgres:12
    ports:
      - 5435:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: posts-db
    volumes:
      - postdata:/var/lib/postgresql/data2


  postgres:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
  keycloak:
    image: quay.io/keycloak/keycloak:legacy
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_SCHEMA: public
      DB_PASSWORD: password
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: Pa55w0rd
      # Uncomment the line below if you want to specify JDBC parameters. The parameter below is just an example, and it shouldn't be used in production without knowledge. It is highly recommended that you read the PostgreSQL JDBC driver documentation in order to use it.
      #JDBC_PARAMS: "ssl=true"
    ports:
      - 8087:8080
    depends_on:
      - postgres





volumes:
  postdata:
    external: false
  followdata:
    external: false
  postgres_data:
    driver: local

