


on:
  push:
    branches:
      - main

name: AzureDeploy

jobs:

    deploy:
      runs-on: ubuntu-latest
      steps:

          
      # checkout code from repo
      - name: checkout repo
        uses: actions/checkout@v1
          
      - name: Execute restart command
        run: 
            sh 'azureVm.sh'
