

on:
  push:
    branches:
      - production

name: AzureDeploy

jobs:

    deploy:
      runs-on: ubuntu-latest
      steps:

      - name: Update server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PROD_IP }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PROD_KEY }}
          script: |
            cd Backend
            sudo docker-compose stop
            sudo docker-compose pull
            sudo docker-compose up --detach
