


on:
  push:
    branches:
      - develop

name: AzureDeploy

jobs:

    deploy:
      runs-on: ubuntu-latest
      env:
        KEY: ${{ secrets.DEV_KEY }}
        USERNAME: ${{ secrets.USERNAME }}
        IP: ${{ secrets.DEV_IP }}
      steps:

          
      # checkout code from repo
      - name: checkout repo
        uses: actions/checkout@v1
          
      - name: Execute restart command
        run: ./azureVm.sh
